In [1]:
import pandas as pd

In [2]:
urlJ = "/bigdata/jelicicna/output_datasets/cleaned_data_nextbike_2021-06.csv.gz"
urlM = "/bigdata/jelicicna/output_datasets/cleaned_data_nextbike_2021-03.csv.gz"

dfJ = pd.read_csv(urlJ, sep=';', parse_dates=True, low_memory=False)
dfM = pd.read_csv(urlM, sep=';', parse_dates=True, low_memory=False)

In [3]:
dfJ.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 527944 entries, 0 to 527943
Data columns (total 25 columns):
lat                   527944 non-null float64
lng                   527944 non-null float64
time_begin            527944 non-null object
time_end              527944 non-null object
name                  527944 non-null object
address               1256 non-null object
bike                  527944 non-null bool
bike_racks            527944 non-null int64
bikes                 527944 non-null int64
booked_bikes          527944 non-null int64
free_racks            527944 non-null int64
free_special_racks    527944 non-null int64
maintenance           527944 non-null bool
number                527944 non-null int64
place_type            527944 non-null int64
rack_locks            527944 non-null bool
special_racks         527944 non-null int64
spot                  527944 non-null bool
terminal_type         0 non-null float64
uid                   527944 non-null int64
city                  527944 non-null object
country_code          527944 non-null object
company               527944 non-null object
timezone              527944 non-null object
available_bikes       527944 non-null int64
dtypes: bool(4), float64(3), int64(10), object(8)
memory usage: 86.6+ MB

In [4]:
dfM.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73447 entries, 0 to 73446
Data columns (total 25 columns):
lat                   73447 non-null float64
lng                   73447 non-null float64
time_begin            73447 non-null object
time_end              73447 non-null object
name                  73447 non-null object
address               589 non-null object
bike                  73447 non-null bool
bike_racks            73447 non-null int64
bikes                 73447 non-null int64
booked_bikes          73447 non-null int64
free_racks            73447 non-null int64
free_special_racks    73447 non-null int64
maintenance           73447 non-null bool
number                73447 non-null int64
place_type            73447 non-null int64
rack_locks            73447 non-null bool
special_racks         73447 non-null int64
spot                  73447 non-null bool
terminal_type         0 non-null float64
uid                   73447 non-null int64
city                  73447 non-null object
country_code          73447 non-null object
company               73447 non-null object
timezone              73447 non-null object
available_bikes       73447 non-null int64
dtypes: bool(4), float64(3), int64(10), object(8)
memory usage: 12.0+ MB

In [5]:
dfJ.head(30)

,lat,lng,time_begin,time_end,name,address,bike,bike_racks,bikes,booked_bikes,...,rack_locks,special_racks,spot,terminal_type,uid,city,country_code,company,timezone,available_bikes
0,50.940676,7.025754,2021-06-01 00:00:01.822984,2021-06-01 04:41:01.817536,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,45936447,Köln,DE,Nextbike,Europe/Berlin,1364
1,50.940707,7.025848,2021-06-01 04:42:02.428941,2021-06-01 06:24:02.974745,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,45936447,Köln,DE,Nextbike,Europe/Berlin,1388
2,50.940689,7.025822,2021-06-01 06:25:01.483547,2021-06-01 11:25:03.330928,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,45936447,Köln,DE,Nextbike,Europe/Berlin,1386
3,50.940573,7.025721,2021-06-01 11:26:01.840005,2021-06-01 16:25:01.643259,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,45936447,Köln,DE,Nextbike,Europe/Berlin,1379
4,50.941218,7.026487,2021-06-01 16:26:02.133010,2021-06-01 16:26:02.133010,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46018839,Köln,DE,Nextbike,Europe/Berlin,1340
5,50.941098,7.026292,2021-06-01 16:27:01.635277,2021-06-01 18:12:01.944135,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46018839,Köln,DE,Nextbike,Europe/Berlin,1342
6,50.940298,7.030703,2021-06-01 18:31:02.692551,2021-06-01 18:32:02.365261,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1289
7,50.940209,7.030663,2021-06-01 18:33:01.857533,2021-06-01 21:24:01.985448,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1285
8,50.940284,7.030637,2021-06-01 21:25:01.490268,2021-06-02 02:25:03.028519,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1335
9,50.940191,7.030642,2021-06-02 02:26:01.518947,2021-06-02 06:25:01.609141,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1402
10,50.940307,7.030665,2021-06-02 06:26:02.450970,2021-06-02 11:26:01.718747,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1399
11,50.940258,7.030705,2021-06-02 11:27:02.215187,2021-06-02 16:26:02.403037,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1363
12,50.940169,7.030598,2021-06-02 16:27:01.897826,2021-06-02 21:26:03.278257,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1308
13,50.940040,7.030713,2021-06-02 21:27:01.764952,2021-06-03 06:10:02.118492,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1314
14,50.940129,7.030662,2021-06-03 06:11:01.651383,2021-06-03 11:11:01.530316,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1387
15,50.940200,7.030634,2021-06-03 11:12:02.815308,2021-06-03 16:11:02.172161,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1373
16,50.940293,7.030678,2021-06-03 16:12:01.663197,2021-06-03 21:11:02.037719,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1316
17,50.940164,7.030623,2021-06-03 21:12:01.525204,2021-06-04 02:11:02.715255,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1335
18,50.940200,7.030626,2021-06-04 02:12:02.364776,2021-06-04 06:10:02.701258,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1369
19,50.940249,7.030662,2021-06-04 06:11:02.206331,2021-06-04 11:10:01.769389,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1373
20,50.940169,7.030598,2021-06-04 11:11:02.293946,2021-06-04 16:10:01.608898,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1326
21,50.940191,7.030626,2021-06-04 16:11:02.095834,2021-06-04 21:10:01.953255,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1306
22,50.940191,7.030649,2021-06-04 21:11:01.469824,2021-06-05 02:10:01.582262,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1370
23,50.940218,7.030626,2021-06-05 02:11:02.210315,2021-06-05 06:10:01.499826,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1383
24,50.940342,7.030686,2021-06-05 06:11:01.978704,2021-06-05 11:10:01.457893,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1390
25,50.940178,7.030616,2021-06-05 11:11:01.965607,2021-06-05 13:23:01.850009,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46031932,Köln,DE,Nextbike,Europe/Berlin,1335
26,50.927836,6.965876,2021-06-05 13:56:01.656734,2021-06-05 13:59:02.122724,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46342389,Köln,DE,Nextbike,Europe/Berlin,1317
27,50.927742,6.965850,2021-06-05 14:00:01.606096,2021-06-05 16:10:02.722002,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46342389,Köln,DE,Nextbike,Europe/Berlin,1310
28,50.927813,6.966093,2021-06-05 16:11:02.407611,2021-06-05 21:10:02.431661,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46342389,Köln,DE,Nextbike,Europe/Berlin,1314
29,50.927569,6.965552,2021-06-05 21:11:01.933226,2021-06-06 02:10:02.014055,BIKE 220764,NaN,True,0,1,0,...,False,0,False,NaN,46342389,Köln,DE,Nextbike,Europe/Berlin,1354