In [1]:
import pandas as pd
import math as mt
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import statistics
from itertools import islice

In [2]:
from pylab import rcParams
rcParams['figure.figsize'] = 16, 9

In [3]:
url = "distance_and_ride_time_data_nextbike_2020-06cc.csv"
url_pr = "processed_data_nextbike_2020-06cc.csv"
df = pd.read_csv(url, sep=';', low_memory=False)
df_pr = pd.read_csv(url, sep=';', low_memory=False)

In [4]:
pd.set_option('display.max_rows()', None)

#### Function for limiting possible lengths of distances to 2500meters in order to work with one part of data without extreme values

In [5]:
def drop_duplicates(l):
    '''Droping duplicates from a list while maintaining order'''
    seen = set()
    seen_add = seen.add
    return [x for x in l if not (x in seen or seen_add(x))]

In [6]:
def short_list(time):
    return [x for x in sr[time] if x < 2500]

In [7]:
df = df.drop(['bike', 'bike_racks', 'bikes', 'booked_bikes', 'free_racks', 'free_special_racks', 'maintenance', 'number', 
              'place_type', 'rack_locks', 'special_racks', 'spot', 'terminal_type', 'city',
              'country_code', 'company', 'timezone', 'available_bikes'], axis=1)

In [8]:
df.size

859032

In [9]:
df_pr.size

2147580

In [10]:
rows_with_nan = []
for index, row in df.iterrows():
    is_nan_series = row.isnull()
    if is_nan_series.any():
        rows_with_nan.append(index)

In [11]:
df_adr = df.drop(rows_with_nan, axis=0)

In [12]:
df_adr.head()

,lat_begin,lng_begin,lat_end,lng_end,ride_begin,ride_end,ride_time_minutes,distance,uid_begin,uid_end,address,name
43,50.962633,7.003422,50.982984,6.943306,2020-06-23 15:16:01.469897,2020-06-23 15:51:02.883198,35.0,4780.0,31412495,31428321,Buchheimer Str. 53,BIKE 21261
384,50.937337,6.982906,50.947377,6.945150,2020-06-04 10:20:02.015185,2020-06-04 10:32:02.176659,12.0,2872.0,30610825,30611125,"Willy-Brandt-Platz 3, 50679 Köln",BIKE 21142
389,51.987538,5.891279,50.949319,6.952410,2020-06-10 17:26:02.325793,2020-06-10 17:27:01.832579,1.0,136898.0,30844480,30844589,Schilderstr,BIKE 21142
390,50.949319,6.952410,50.930628,6.940701,2020-06-10 19:16:01.961847,2020-06-10 19:42:01.696540,26.0,2235.0,30844589,30852169,Schildergasse,BIKE 21142
411,42.841646,-82.880387,50.937619,7.006554,2020-06-19 10:48:01.493559,2020-06-19 10:49:02.138013,1.0,6459100.0,31243469,31243504,Hollwegstraße,BIKE 21142

In [13]:
address_list = df_adr.index.to_list()

In [14]:
previous_address_list = [(i-1) for i in address_list]
following_address_list = [(i+1) for i in address_list]

In [15]:
overview_list = previous_address_list + address_list + following_address_list
overview_list.sort()
overview_list = drop_duplicates(overview_list)

In [16]:
df_suspicious_indexes = df.loc[overview_list]

In [17]:
df_suspicious_indexes.head()

,lat_begin,lng_begin,lat_end,lng_end,ride_begin,ride_end,ride_time_minutes,distance,uid_begin,uid_end,address,name
42,50.985846,6.945063,50.962633,7.003422,2020-06-23 08:18:01.578288,2020-06-23 08:46:01.778788,28.0,4835.0,31294157,31412495,NaN,BIKE 21261
43,50.962633,7.003422,50.982984,6.943306,2020-06-23 15:16:01.469897,2020-06-23 15:51:02.883198,35.0,4780.0,31412495,31428321,Buchheimer Str. 53,BIKE 21261
44,50.982984,6.943306,50.990532,6.942997,2020-06-23 17:33:02.078141,2020-06-23 17:40:01.829675,7.0,840.0,31428321,31435730,NaN,BIKE 21261
383,50.939328,7.003626,50.937337,6.982906,2020-06-04 10:16:01.961973,2020-06-04 10:18:02.005541,2.0,1469.0,30552315,30610825,NaN,BIKE 21142
384,50.937337,6.982906,50.947377,6.945150,2020-06-04 10:20:02.015185,2020-06-04 10:32:02.176659,12.0,2872.0,30610825,30611125,"Willy-Brandt-Platz 3, 50679 Köln",BIKE 21142

In [18]:
previous_index = overview_list[0]
previous_distance = df_suspicious_indexes.iloc[0]['distance']
suspicious_return_trips = []
for index,row in islice(df_suspicious_indexes.iterrows(), 1, None):
    if (row['distance'] == previous_distance):
        suspicious_return_trips.append(previous_index)
        suspicious_return_trips.append(index)
        
    previous_index = index
    previous_distance = row['distance']

In [19]:
suspicious_return_trips

[388, 389, 56136, 56137]

In [20]:
suspicious_distances = []
for index,row in df.iterrows():
    if (row['distance'] > 20000):
        suspicious_distances.append(index)

In [21]:
suspicious_distances

[388,
 389,
 410,
 411,
 10694,
 10695,
 17436,
 17437,
 28469,
 28470,
 29148,
 49220,
 49221,
 56852,
 60949,
 60950,
 65843,
 71254]

In [ ]:
#suspicious_times = []
#for index, row in df.iterrows():
    #if row['ride_time_minutes'] > 2880:
        #suspicious_times.append(index)

In [ ]:
suspicious_times #remains to be investigated

In [22]:
df.loc[71254]

lat_begin                               50.9192
lng_begin                               6.94059
lat_end                                 24.8874
lng_end                                 85.6735
ride_begin           2020-06-08 10:36:01.722689
ride_end             2020-06-15 18:13:02.131704
ride_time_minutes                         10537
distance                            7.11842e+06
uid_begin                              30734840
uid_end                                31077661
address                                     NaN
name                                 BIKE 22829
Name: 71254, dtype: object

In [23]:
single_bike1 = df[df['name']== 'BIKE 22829' ] #the bike that appears in India
single_bike1

,lat_begin,lng_begin,lat_end,lng_end,ride_begin,ride_end,ride_time_minutes,distance,uid_begin,uid_end,address,name
71237,50.930883,6.982423,50.936483,6.973939,2020-06-02 19:52:01.597082,2020-06-02 20:08:02.937887,16.0,861.0,30547506,30549344,NaN,BIKE 22829
71238,50.936483,6.973939,50.931560,6.995322,2020-06-02 21:12:01.520129,2020-06-02 21:39:02.379746,27.0,1596.0,30549344,30552884,NaN,BIKE 22829
71239,50.931560,6.995322,50.918304,6.978265,2020-06-02 22:18:01.870950,2020-06-02 22:36:03.357806,18.0,1898.0,30552884,30555231,NaN,BIKE 22829
71240,50.918304,6.978265,50.921531,6.932361,2020-06-02 23:07:01.481846,2020-06-03 11:21:02.256313,734.0,3239.0,30555231,30566924,NaN,BIKE 22829
71241,50.921531,6.932361,50.931155,6.933808,2020-06-03 13:11:01.594453,2020-06-03 13:57:01.450742,46.0,1075.0,30566924,30572830,NaN,BIKE 22829
71242,50.931155,6.933808,50.933774,6.927543,2020-06-03 16:03:01.624929,2020-06-03 16:19:02.404938,16.0,527.0,30572830,30579261,NaN,BIKE 22829
71243,50.933774,6.927543,50.955430,6.907188,2020-06-03 16:56:01.602248,2020-06-03 19:56:02.608255,180.0,2799.0,30579261,30590948,NaN,BIKE 22829
71244,50.955430,6.907188,50.917030,6.928348,2020-06-03 21:52:01.892672,2020-06-04 22:32:01.932721,1480.0,4521.0,30590948,30603587,NaN,BIKE 22829
71245,50.917030,6.928348,50.934909,6.949900,2020-06-05 08:51:02.546428,2020-06-05 09:39:02.252019,48.0,2498.0,30603587,30642905,NaN,BIKE 22829
71246,50.934909,6.949900,50.926665,6.936464,2020-06-05 12:55:02.038601,2020-06-05 15:14:01.662169,139.0,1315.0,30642905,30651055,NaN,BIKE 22829
71247,50.926665,6.936464,50.915781,6.893694,2020-06-05 20:22:01.842273,2020-06-05 22:52:01.627699,150.0,3234.0,30651055,30662383,NaN,BIKE 22829
71248,50.915781,6.893694,50.914819,6.893915,2020-06-05 23:00:02.248172,2020-06-05 23:01:02.590441,1.0,108.0,30662383,30665738,NaN,BIKE 22829
71249,50.914819,6.893915,50.914989,6.893860,2020-06-05 23:01:02.590441,2020-06-05 23:02:02.106603,1.0,19.0,30665738,30665769,NaN,BIKE 22829
71250,50.914989,6.893860,50.926404,6.936477,2020-06-06 00:01:02.854529,2020-06-06 02:16:01.484593,135.0,3247.0,30665769,30667179,NaN,BIKE 22829
71251,50.926404,6.936477,50.937552,6.891816,2020-06-06 10:29:02.116894,2020-06-06 18:32:01.515360,483.0,3367.0,30667179,30682948,NaN,BIKE 22829
71252,50.937552,6.891816,50.941511,6.957075,2020-06-07 17:11:01.913476,2020-06-07 18:40:01.946605,89.0,4595.0,30682948,30729553,NaN,BIKE 22829
71253,50.941511,6.957075,50.919214,6.940593,2020-06-07 20:12:01.592239,2020-06-07 22:43:02.573555,151.0,2736.0,30729553,30734840,NaN,BIKE 22829
71254,50.919214,6.940593,24.887449,85.673490,2020-06-08 10:36:01.722689,2020-06-15 18:13:02.131704,10537.0,7118417.0,30734840,31077661,NaN,BIKE 22829

In [26]:
single_bike2 = df[df['name']== 'BIKE 22447' ] #the bike that spent days in Bonn
single_bike2

,lat_begin,lng_begin,lat_end,lng_end,ride_begin,ride_end,ride_time_minutes,distance,uid_begin,uid_end,address,name
29151,50.957318,6.994188,50.957516,7.011543,2020-06-17 13:59:01.705480,2020-06-17 14:16:02.180207,17.0,1216.0,31148628,31159806,NaN,BIKE 22447
29152,50.957516,7.011543,50.945297,7.004668,2020-06-17 15:13:02.241147,2020-06-17 17:20:01.750001,127.0,1442.0,31159806,31169450,NaN,BIKE 22447
29153,50.945297,7.004668,50.943636,7.002369,2020-06-17 18:22:02.642355,2020-06-17 18:48:02.413702,26.0,245.0,31169450,31175407,NaN,BIKE 22447
29154,50.943636,7.002369,50.944949,7.002819,2020-06-17 18:52:02.429497,2020-06-17 19:04:01.922568,12.0,149.0,31175407,31176425,NaN,BIKE 22447
29155,50.944949,7.002819,50.955271,7.006061,2020-06-17 19:53:02.101423,2020-06-17 20:06:02.164899,13.0,1170.0,31176425,31179859,NaN,BIKE 22447
29156,50.955271,7.006061,50.944826,7.002802,2020-06-17 23:14:02.364191,2020-06-18 03:53:02.247941,279.0,1184.0,31179859,31187527,NaN,BIKE 22447
29157,50.944826,7.002802,50.935495,6.987459,2020-06-18 08:20:02.362989,2020-06-18 09:06:02.839341,46.0,1494.0,31187527,31196351,NaN,BIKE 22447
29158,50.935495,6.987459,50.944814,7.003258,2020-06-18 13:42:02.048855,2020-06-18 13:53:02.091743,11.0,1517.0,31196351,31207032,NaN,BIKE 22447
29159,50.944814,7.003258,50.938151,6.997724,2020-06-18 15:05:01.561201,2020-06-18 15:12:01.957368,7.0,836.0,31207032,31210504,NaN,BIKE 22447
29160,50.938151,6.997724,50.945071,7.005121,2020-06-18 15:27:01.952365,2020-06-18 15:36:01.918165,9.0,928.0,31210504,31211601,NaN,BIKE 22447
29161,50.945071,7.005121,50.934219,7.009012,2020-06-18 16:54:02.276554,2020-06-18 17:06:02.233913,12.0,1238.0,31211601,31216328,NaN,BIKE 22447
29162,50.934219,7.009012,50.945282,7.004990,2020-06-18 19:18:02.160585,2020-06-18 19:47:02.417744,29.0,1262.0,31216328,31224525,NaN,BIKE 22447
29163,50.945282,7.004990,50.935232,7.012635,2020-06-18 20:58:01.687343,2020-06-18 21:34:01.607286,36.0,1240.0,31224525,31229412,NaN,BIKE 22447
29164,50.935232,7.012635,50.939694,7.008987,2020-06-18 22:04:02.216855,2020-06-18 22:13:01.989490,9.0,558.0,31229412,31230752,NaN,BIKE 22447
29165,50.939694,7.008987,50.939245,7.009216,2020-06-18 22:13:01.989490,2020-06-18 22:14:01.480305,1.0,52.0,31230752,31230925,NaN,BIKE 22447
29166,50.939245,7.009216,50.939118,7.028132,2020-06-19 01:50:01.532538,2020-06-19 02:11:01.461707,21.0,1326.0,31230925,31235430,NaN,BIKE 22447
29167,50.939118,7.028132,50.972285,7.006742,2020-06-19 12:43:02.340778,2020-06-19 13:20:01.767981,37.0,3982.0,31235430,31247508,NaN,BIKE 22447
29168,50.972285,7.006742,50.977348,7.000424,2020-06-20 10:59:01.506958,2020-06-20 21:41:01.678166,642.0,716.0,31247508,31310395,NaN,BIKE 22447
29169,50.977348,7.000424,50.975296,7.004651,2020-06-21 11:58:01.573910,2020-06-21 15:41:01.939301,223.0,374.0,31310395,31333929,NaN,BIKE 22447
29170,50.975296,7.004651,50.975265,7.004920,2020-06-21 15:47:01.505326,2020-06-21 15:48:02.966769,1.0,19.0,31333929,31334317,NaN,BIKE 22447
29171,50.975265,7.004920,50.973650,7.005635,2020-06-21 17:07:02.151711,2020-06-21 18:39:01.966694,92.0,186.0,31334317,31343188,NaN,BIKE 22447
29172,50.973650,7.005635,50.973627,7.006042,2020-06-21 18:46:01.916459,2020-06-21 18:47:01.440413,1.0,29.0,31343188,31343658,NaN,BIKE 22447
29173,50.973627,7.006042,50.928508,6.974619,2020-06-22 07:53:02.149397,2020-06-22 09:43:02.014675,110.0,5480.0,31343658,31364613,NaN,BIKE 22447
29174,50.928508,6.974619,50.910042,6.947782,2020-06-22 15:46:01.599066,2020-06-22 16:06:01.818868,20.0,2786.0,31364613,31378872,NaN,BIKE 22447
29175,50.910042,6.947782,50.928912,6.974579,2020-06-22 16:32:02.225229,2020-06-22 20:22:02.833643,230.0,2817.0,31378872,31395554,NaN,BIKE 22447
29176,50.928912,6.974579,50.938195,6.940551,2020-06-22 20:33:02.025683,2020-06-22 21:04:01.820987,31.0,2599.0,31395554,31397613,NaN,BIKE 22447
29177,50.938195,6.940551,50.938266,6.940824,2020-06-22 21:11:02.378401,2020-06-22 21:12:01.895862,1.0,21.0,31397613,31398248,NaN,BIKE 22447
29178,50.938266,6.940824,50.955258,6.930631,2020-06-22 21:54:01.590337,2020-06-22 22:09:01.476106,15.0,2020.0,31398248,31400848,NaN,BIKE 22447
29179,50.955258,6.930631,50.956141,6.930915,2020-06-23 09:29:01.517846,2020-06-23 09:59:02.928559,30.0,100.0,31400848,31414819,NaN,BIKE 22447
29180,50.956141,6.930915,50.956926,6.939530,2020-06-23 11:18:03.133705,2020-06-23 11:28:02.143874,10.0,610.0,31414819,31417532,NaN,BIKE 22447
29181,50.956926,6.939530,50.955328,6.931143,2020-06-23 11:29:01.707063,2020-06-23 11:35:02.863272,6.0,614.0,31417532,31417834,NaN,BIKE 22447
29182,50.955328,6.931143,50.962663,6.957897,2020-06-23 12:42:02.719045,2020-06-23 12:58:01.504295,16.0,2044.0,31417834,31420717,NaN,BIKE 22447
29183,50.962663,6.957897,50.938575,6.943954,2020-06-23 14:37:01.737325,2020-06-23 15:02:02.224259,25.0,2852.0,31420717,31426225,NaN,BIKE 22447
29184,50.938575,6.943954,50.960915,6.952029,2020-06-23 18:05:01.852648,2020-06-23 18:52:01.950062,47.0,2549.0,31426225,31439206,NaN,BIKE 22447
29185,50.960915,6.952029,50.932608,6.872026,2020-06-23 19:50:01.733566,2020-06-23 20:49:01.789093,59.0,6430.0,31439206,31448169,NaN,BIKE 22447
29186,50.932608,6.872026,50.936494,6.924187,2020-06-23 23:24:02.732179,2020-06-24 00:17:02.387172,53.0,3682.0,31448169,31456189,NaN,BIKE 22447
29187,50.936494,6.924187,50.932129,6.988922,2020-06-24 00:32:01.471198,2020-06-24 04:55:02.023285,263.0,4564.0,31456189,31457724,NaN,BIKE 22447
29188,50.932129,6.988922,50.935715,6.998759,2020-06-24 05:51:02.172146,2020-06-24 06:25:01.585558,34.0,797.0,31457724,31460774,NaN,BIKE 22447
29189,50.935715,6.998759,50.927715,6.996106,2020-06-24 08:26:02.307640,2020-06-24 08:35:02.345852,9.0,909.0,31460774,31464262,NaN,BIKE 22447
29190,50.927715,6.996106,50.935594,6.999373,2020-06-24 08:48:02.277086,2020-06-24 08:55:02.317877,7.0,906.0,31464262,31464903,NaN,BIKE 22447
29191,50.935594,6.999373,50.932566,6.997855,2020-06-24 12:37:01.608538,2020-06-24 13:25:02.672614,48.0,353.0,31464903,31472421,NaN,BIKE 22447
29192,50.932566,6.997855,50.943072,6.995863,2020-06-24 14:39:01.521738,2020-06-24 14:51:02.413923,12.0,1177.0,31472421,31477663,NaN,BIKE 22447
29193,50.943072,6.995863,50.938402,7.005428,2020-06-24 17:02:02.146749,2020-06-24 17:12:02.238028,10.0,848.0,31477663,31484504,NaN,BIKE 22447
29194,50.938402,7.005428,50.938424,7.005598,2020-06-24 17:18:02.345269,2020-06-24 17:19:01.851571,1.0,12.0,31484504,31484961,NaN,BIKE 22447
29195,50.938424,7.005598,50.964148,6.980851,2020-06-24 17:50:02.920216,2020-06-24 18:12:02.852406,22.0,3346.0,31484961,31487993,NaN,BIKE 22447

In [ ]:
#single_bike3 = df_no_adr[df_no_adr['name']== 'BIKE 22385' ]
#single_bike3

In [27]:
no_duplicates = set(suspicious_distances) - set(suspicious_return_trips)

In [29]:
suspicious_indexes = suspicious_return_trips + list(no_duplicates)
suspicious_indexes

[388,
 389,
 56136,
 56137,
 49220,
 49221,
 10694,
 10695,
 17436,
 65843,
 56852,
 28469,
 28470,
 60949,
 60950,
 71254,
 410,
 411,
 29148,
 17437]

In [ ]:
#This is to be used only if we want to include the data about the bike that spent days out of Cologne in the list for droping
#out_of_cologne = set(single_bike2.index)
#list_for_dropping = set(suspicious_indexes) - out_of_cologne
#list_for_dropping = suspicious_indexes + list(list_for_dropping)

In [30]:
df_no = df_pr.drop(suspicious_indexes, axis=0)
df_no.reset_index(inplace=True)
df_no.drop('index', axis=1, inplace=True)

In [31]:
df_no.head(50)

,lat_begin,lng_begin,lat_end,lng_end,ride_begin,ride_end,ride_time_minutes,distance,uid_begin,uid_end,...,place_type,rack_locks,special_racks,spot,terminal_type,city,country_code,company,timezone,available_bikes
0,50.967380,6.913591,50.968653,6.909912,2020-06-01 11:23:02.135730,2020-06-01 11:52:01.971278,29.0,294.0,30468631,30480098,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1058
1,50.968653,6.909912,50.972235,6.924658,2020-06-05 17:07:01.701984,2020-06-05 19:36:02.939119,149.0,1107.0,30480098,30654954,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1079
2,50.972235,6.924658,50.954284,6.919008,2020-06-05 21:19:02.341096,2020-06-05 23:04:02.169224,105.0,2035.0,30654954,30665132,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1089
3,50.954284,6.919008,50.955787,6.914857,2020-06-05 23:30:02.456473,2020-06-06 04:53:01.679870,323.0,335.0,30665132,30669192,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1079
4,50.955787,6.914857,50.932989,6.922490,2020-06-06 09:38:02.380791,2020-06-06 09:58:01.499404,20.0,2592.0,30669192,30673723,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1094
5,50.932989,6.922490,50.936811,6.922821,2020-06-06 14:32:02.513259,2020-06-06 15:13:01.452866,41.0,426.0,30673723,30683067,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1098
6,50.936811,6.922821,50.936704,6.963254,2020-06-06 16:22:02.042554,2020-06-06 17:20:02.849924,58.0,2834.0,30683067,30690361,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1053
7,50.936704,6.963254,50.935375,6.956512,2020-06-06 17:25:01.986203,2020-06-06 17:31:02.264822,6.0,495.0,30690361,30691326,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1062
8,50.935375,6.956512,50.937103,6.962170,2020-06-06 17:37:02.155707,2020-06-06 17:44:01.614297,7.0,441.0,30691326,30691955,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1061
9,50.937103,6.962170,50.906010,6.956364,2020-06-06 19:57:01.447900,2020-06-06 20:29:01.743729,32.0,3482.0,30691955,30699364,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1059
10,50.906010,6.956364,50.929851,6.926177,2020-06-09 18:59:01.593563,2020-06-10 01:34:01.774903,395.0,3393.0,30699364,30806788,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1067
11,50.929851,6.926177,50.936285,6.952587,2020-06-10 07:46:02.091666,2020-06-10 08:11:02.265093,25.0,1985.0,30806788,30822579,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1081
12,50.936285,6.952587,50.936903,6.948938,2020-06-10 08:23:02.800322,2020-06-10 08:44:01.663130,21.0,265.0,30822579,30823489,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1083
13,50.936903,6.948938,50.913170,6.928186,2020-06-10 18:11:02.107113,2020-06-10 18:45:01.929566,34.0,3014.0,30823489,30848436,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1085
14,50.913170,6.928186,50.949752,6.954611,2020-06-10 22:40:03.529728,2020-06-10 23:51:01.508981,71.0,4471.0,30848436,30860266,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1116
15,50.949752,6.954611,50.934485,6.941367,2020-06-11 08:25:01.716009,2020-06-11 09:33:01.881931,68.0,1935.0,30860266,30868810,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1066
16,50.934485,6.941367,50.934722,6.940625,2020-06-11 09:33:01.881931,2020-06-11 09:34:02.728244,1.0,58.0,30868810,30869911,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1136
17,50.934722,6.940625,50.933272,6.940386,2020-06-11 12:30:01.651259,2020-06-11 13:25:01.694348,55.0,162.0,30869911,30875623,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1136
18,50.933272,6.940386,50.908151,6.963467,2020-06-11 16:07:02.659821,2020-06-11 16:35:01.637428,28.0,3229.0,30875623,30883875,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1110
19,50.908151,6.963467,50.934243,6.941763,2020-06-11 19:16:01.849199,2020-06-12 03:42:02.042807,506.0,3277.0,30883875,30895118,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1118
20,50.934243,6.941763,50.949758,6.965345,2020-06-12 08:18:01.742342,2020-06-12 08:57:02.185406,39.0,2390.0,30895118,30912077,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1113
21,50.949758,6.965345,50.943510,6.943475,2020-06-12 09:58:02.300078,2020-06-12 10:17:02.426658,19.0,1683.0,30912077,30915311,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1116
22,50.943510,6.943475,50.949213,6.952046,2020-06-12 12:32:02.049151,2020-06-12 15:11:02.541919,159.0,874.0,30915311,30920585,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1116
23,50.949213,6.952046,50.961568,7.005907,2020-06-12 16:26:02.677177,2020-06-12 17:52:01.819986,86.0,4016.0,30920585,30937115,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1114
24,50.961568,7.005907,50.933382,6.975790,2020-06-12 20:24:01.794287,2020-06-12 21:17:02.069723,53.0,3779.0,30937115,30950971,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1135
25,50.933382,6.975790,50.928606,6.974532,2020-06-13 10:04:02.088722,2020-06-13 10:20:02.007531,16.0,539.0,30950971,30969853,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1137
26,50.928606,6.974532,50.936667,6.976264,2020-06-13 10:49:02.515785,2020-06-13 12:43:02.009853,114.0,905.0,30969853,30973712,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1148
27,50.936667,6.976264,50.937037,6.976590,2020-06-13 15:41:02.386008,2020-06-13 18:06:05.909220,145.0,47.0,30973712,30984900,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1095
28,50.937037,6.976590,50.943798,7.010036,2020-06-13 18:06:05.909220,2020-06-13 18:56:01.577922,50.0,2462.0,30984900,30993887,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1132
29,50.943798,7.010036,50.956399,7.008547,2020-06-13 21:18:02.068301,2020-06-13 22:09:01.807275,51.0,1405.0,30993887,31001984,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1116
30,50.956399,7.008547,50.962283,7.013607,2020-06-15 20:15:01.809691,2020-06-15 20:47:02.016257,32.0,744.0,31001984,31085640,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1119
31,50.962283,7.013607,50.964998,7.014928,2020-06-16 06:44:02.492977,2020-06-16 09:02:02.042917,138.0,316.0,31085640,31098341,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1112
32,50.964998,7.014928,50.957877,7.012483,2020-06-16 11:52:01.497526,2020-06-16 14:32:01.802340,160.0,810.0,31098341,31112178,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1137
33,50.957877,7.012483,50.964598,7.014343,2020-06-16 14:37:01.816941,2020-06-16 14:45:03.064487,8.0,759.0,31112178,31113222,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1113
34,50.964598,7.014343,50.962199,7.004171,2020-06-16 18:47:01.472144,2020-06-16 18:57:02.302005,10.0,761.0,31113222,31127184,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1117
35,50.962199,7.004171,50.986003,6.945431,2020-06-16 21:07:02.171817,2020-06-16 21:37:02.164652,30.0,4892.0,31127184,31135842,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1125
36,50.986003,6.945431,50.987770,6.940853,2020-06-17 19:33:02.363387,2020-06-17 19:41:03.213017,8.0,376.0,31135842,31178460,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1109
37,50.987770,6.940853,50.985061,6.946331,2020-06-18 09:23:01.473932,2020-06-18 10:00:02.782364,37.0,488.0,31178460,31198213,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1150
38,50.985061,6.946331,50.983425,6.947568,2020-06-18 14:49:02.328949,2020-06-18 16:29:01.452049,100.0,202.0,31198213,31214236,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1168
39,50.983425,6.947568,50.985922,6.966882,2020-06-19 23:42:01.453294,2020-06-20 00:17:02.068867,35.0,1381.0,31214236,31275049,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1165
40,50.985922,6.966882,50.979997,6.948084,2020-06-20 02:20:01.689020,2020-06-20 02:53:01.988012,33.0,1472.0,31275049,31279161,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1141
41,50.979997,6.948084,50.985846,6.945063,2020-06-20 14:44:01.516039,2020-06-20 15:40:02.109373,56.0,684.0,31279161,31294157,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1160
42,50.985846,6.945063,50.962633,7.003422,2020-06-23 08:18:01.578288,2020-06-23 08:46:01.778788,28.0,4835.0,31294157,31412495,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1163
43,50.962633,7.003422,50.982984,6.943306,2020-06-23 15:16:01.469897,2020-06-23 15:51:02.883198,35.0,4780.0,31412495,31428321,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1164
44,50.982984,6.943306,50.990532,6.942997,2020-06-23 17:33:02.078141,2020-06-23 17:40:01.829675,7.0,840.0,31428321,31435730,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1170
45,50.990532,6.942997,51.022268,6.897904,2020-06-27 18:29:02.027434,2020-06-27 19:09:02.332452,40.0,4735.0,31435730,31651089,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1158
46,51.022268,6.897904,51.024692,6.916606,2020-06-27 20:09:01.508699,2020-06-27 20:27:01.510665,18.0,1336.0,31651089,31656079,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1161
47,51.024692,6.916606,50.948149,6.952187,2020-06-27 20:56:01.624928,2020-06-28 07:52:02.881800,656.0,8871.0,31656079,31660937,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1150
48,50.948149,6.952187,50.959054,6.972229,2020-06-28 12:03:02.487694,2020-06-28 13:11:01.994412,68.0,1856.0,31660937,31680411,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1171
49,50.959054,6.972229,50.940791,6.969398,2020-06-28 13:37:02.212385,2020-06-28 14:04:01.639181,27.0,2041.0,31680411,31683912,...,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1136

In [ ]:
df_no.to_csv('clust_data_nextbike_2020-06cc.csv', sep=';', index=False)