In [1]:
import pandas as pd
from datetime import datetime
import time
from itertools import islice

In [2]:
def append_new_row(data_frame, row):
    data_frame = data_frame.append({'lat_begin' : row['lat'], 'lng_begin' : row['lng'],
                                'lat_end' : 0, 'lng_end' : 0,
                                'ride_begin' : row['time_end'], 'ride_end' : 0,
                                'ride_time_minutes' : 0,
                                'uid_begin' : row['uid'], 'uid_end' : 0, 'standing_before_ride' : row['standing_time_minutes'],
                                'name' : row['name'], 'address' : row['address'],
                                'bike' : row['bike'], 'bike_racks' : row['bike_racks'], 
                                'bikes' : row['bikes'], 'booked_bikes' : row['booked_bikes'], 
                                'free_racks' : row['free_racks'], 'free_special_racks' : row['free_special_racks'],
                                'maintenance' : row['maintenance'], 'number' : row['number'], 
                                'place_type' : row['place_type'], 'rack_locks' : row['rack_locks'],
                                'special_racks' : row['special_racks'], 'spot' : row['spot'], 
                                'terminal_type' : row['terminal_type'], 'city' : row['city'],
                                'country_code' : row['country_code'], 'company' : row['company'],
                                'timezone' : row['timezone'],
                                'available_bikes' : row['available_bikes']}, ignore_index=True)
    return data_frame

### Processes the data in order to create new column  'ride_time_minutes' 

#### As URL set one of the following:
1. 'cleaned_data_nextbike_yy-mm.csv.gz' if you want to work with original cleaned data 
2. 'processed_data_nextbike_yy-mm.csv.gz' if you want to work with data that has GPS errors removed 

CHANGE NAME OF OUTPUT TO DESCRIBE THE CHOICE

In [3]:
url = "output_datasets/processed_data_nextbike_2020-07.csv.gz"
df = pd.read_csv(url, sep=';', low_memory=False)

In [4]:
fmt = '%Y-%m-%d %H:%M:%S'

In [16]:
pd.set_option('display.max_rows', None)

In [18]:
df["uid"].duplicated().any() #checking if cleaning in notebook @3 was done - there should be no duplicates

False

In [7]:
new_df = pd.DataFrame(columns= ['lat_begin', 'lng_begin', 'lat_end', 'lng_end', 'ride_begin', 'ride_end', 'ride_time_minutes', 
                                'uid_begin', 'uid_end', 'standing_before_ride', 'address', 'name', 'available_bikes', 'bike', 'bike_racks', 'bikes', 
                                'booked_bikes', 'free_racks', 'free_special_racks', 'maintenance', 'number', 
                                'place_type', 'rack_locks', 'special_racks', 'spot', 'terminal_type', 'city',
                                'country_code', 'company', 'timezone'] ) #empty dataframe with the new column structure

In [8]:
bikesToList = df['name'].tolist()
bikesList = list(set(bikesToList))

In [9]:
for name in bikesList: #repeat for each bike/bike name
    single_bike_records = df[df['name']==name]
    first_row_data = single_bike_records.iloc[0]
    last_end_time = first_row_data['time_end']

    new_df = append_new_row(new_df, first_row_data)

    for index, row in islice(single_bike_records.iterrows(), 1, None):
        t_begin = df['time_begin'][index].split('.')[0]
        t_end_previous = last_end_time.split('.')[0]    

        d1 = datetime.strptime(t_begin, fmt)
        d2 = datetime.strptime(t_end_previous, fmt)

        d1_ts = time.mktime(d1.timetuple())
        d2_ts = time.mktime(d2.timetuple())

        minsDiff = round((int(d1_ts-d2_ts) / 60), 0)

        new_df.iloc[-1, new_df.columns.get_loc('ride_time_minutes')] = minsDiff
        new_df.iloc[-1, new_df.columns.get_loc('lat_end')] = row['lat']
        new_df.iloc[-1, new_df.columns.get_loc('lng_end')] = row['lng']
        new_df.iloc[-1, new_df.columns.get_loc('ride_end')] = row['time_begin']
        new_df.iloc[-1, new_df.columns.get_loc('uid_end')] = row['uid']

        last_end_time = row['time_end']
        
        new_df = append_new_row(new_df, row)

KeyboardInterrupt:

In [10]:
new_df.head()

,lat_begin,lng_begin,lat_end,lng_end,ride_begin,ride_end,ride_time_minutes,uid_begin,uid_end,standing_before_ride,address,name,bike,bike_racks,bikes,booked_bikes,free_racks,free_special_racks,maintenance,number,place_type,rack_locks,special_racks,spot,terminal_type,city,country_code,company,timezone,available_bikes
0,50.972917,6.942211,50.943,6.94826,2020-07-01 08:15:01.531643,2020-07-01 08:40:02.243662,25,31791808,31817113,495.0,NaN,BIKE 21739,True,0,1,0,0,0,False,0,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1093
1,50.942994,6.948256,50.9446,6.97302,2020-07-01 09:08:02.524291,2020-07-01 12:38:02.187992,210,31817113,31818971,28.0,NaN,BIKE 21739,True,0,1,0,0,0,False,0,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1162
2,50.944647,6.973024,50.9107,6.96871,2020-07-01 14:34:02.223914,2020-07-01 19:55:02.350584,321,31818971,31850898,116.0,NaN,BIKE 21739,True,0,1,0,0,0,False,0,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1158
3,50.910694,6.968715,50.9432,6.95977,2020-07-01 20:11:01.469569,2020-07-01 20:32:01.602313,21,31850898,31853330,16.0,NaN,BIKE 21739,True,0,1,0,0,0,False,0,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1153
4,50.943172,6.959775,50.961,6.94002,2020-07-01 21:25:02.080594,2020-07-01 21:46:02.170175,21,31853330,31857547,53.0,NaN,BIKE 21739,True,0,1,0,0,0,False,0,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,50.938286,6.959007,50.9567,7.00437,2020-07-09 11:39:01.905045,2020-07-09 12:13:01.729532,34,32224370,32230034,155.0,NaN,BIKE 21243,True,0,1,0,0,0,False,0,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1050
311,50.956728,7.004370,50.9424,6.99845,2020-07-09 13:00:02.667568,2020-07-09 13:12:01.977278,12,32230034,32232783,47.0,NaN,BIKE 21243,True,0,1,0,0,0,False,0,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1027
312,50.942450,6.998455,50.9354,6.99795,2020-07-09 14:22:01.460598,2020-07-09 14:29:01.521893,7,32232783,32235690,70.0,NaN,BIKE 21243,True,0,1,0,0,0,False,0,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1040
313,50.935390,6.997951,50.9341,6.99387,2020-07-09 14:54:02.954207,2020-07-09 15:01:01.608366,7,32235690,32237164,25.0,NaN,BIKE 21243,True,0,1,0,0,0,False,0,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1051
314,50.934124,6.993870,50.9184,6.97802,2020-07-09 15:11:02.055556,2020-07-09 15:39:02.195052,28,32237164,32239112,10.0,NaN,BIKE 21243,True,0,1,0,0,0,False,0,12,False,0,False,NaN,Köln,DE,Nextbike,Europe/Berlin,1056

###  Prevous code assignes 0 values to some features that should be updated trough itteration to contain acctual end values of one ride.
### As a result for each bike there will be one extra row that has not updated values, meaning itteration has reached the end for selected bike and 0 values were not updated. 
### In the following cells we check for rows like that - idealy number of rows shoud match number of bikes

In [ ]:
control_df = new_df[new_df['ride_end'] == 0]
control_df

In [ ]:
len(bikesList)

In [ ]:
incorrect_indexes = list(control_df.index.values)
len(incorrect_indexes)

In [ ]:
for i in incorrect_indexes:
    if i in new_df.index.values:
        new_df.drop(i, inplace=True)

In [ ]:
new_df = new_df.reset_index()

In [ ]:
new_df.drop(['index'], axis=1)

In [ ]:
new_df['ride_time_minutes'].value_counts(dropna=False)

In [ ]:
single_bike = df[df['name']== 'BIKE 21423' ]
single_bike

In [ ]:
single_bike_new = new_df[new_df['name']== 'BIKE 21423' ]
single_bike_new

In [ ]:
new_df.to_csv('rides_table_nextbike_2020-07.csv', sep=';', index=False)